name: Run Function Daily

on:
  schedule:
    - cron: '30 15 * * *' # Ejecuta a las 17:30 CEST todos los días

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment variables
        run: |
          echo "TWITTER_ACCESS_TOKEN=${{ secrets.TWITTER_ACCESS_TOKEN }}" >> $GITHUB_ENV
          echo "TWITTER_ACCESS_TOKEN_SECRET=${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}" >> $GITHUB_ENV
          echo "TWITTER_CONSUMER_KEY=${{ secrets.TWITTER_CONSUMER_KEY }}" >> $GITHUB_ENV
          echo "TWITTER_CONSUMER_SECRET=${{ secrets.TWITTER_CONSUMER_SECRET }}" >> $GITHUB_ENV

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21' 
          distribution: 'temurin'

      - name: Run Maven
        run: |
          mvn clean install

      - name: Compile and run Java application
        run: java -jar target/api_twitter_birthday-1.0-SNAPSHOT.jar
